version: "3.3"

services:
  rapidog-db:
    image: app-db
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    env_file:
      - composer.env
    volumes:
      - db_rapidog:/var/lib/postgresql/data
    networks:
      - rapidog
  worker:
    build: .
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./:/usr/src/app/
    command: "celery -A app.workers.dogs.celery_app worker -Q test-queue -c 1"
    env_file:
      - composer.env
    networks:
      - rapidog

  web-app:
    depends_on:
      - rapidog-db
      - redis
      - rabbitmq
    image: web-app
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - composer.env
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3000:8000
    networks:
      - rapidog

  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1000000000
    ports:
      - 4369:4369
      - 5672:5672
      - 25672:25672
      - 15672:15672
    expose:
      - 4369
      - 5672
      - 25672
      - 15672
    networks:
      - rapidog

  redis:
    image: bitnami/redis:5.0.4
    environment:
      - REDIS_PASSWORD=password123
    ports:
    - 6379:6379
    networks:
      - rapidog

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rapidog
volumes:
  db_rapidog:
networks:
  rapidog:
